/*
   This file was generated automatically by the Mojo IDE version B1.2.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module rom_25 (
    input [3:0] address,
    output reg [19:0] options,
    output reg [7:0] goal
  );
  
  
  
  reg [19:0] options_decimal;
  
  always @* begin
    
    case (address)
      1'h0: begin
        options_decimal = 20'hddddd;
        options = 1'h0;
        goal = 1'h0;
      end
      1'h1: begin
        options_decimal = 20'h1363d;
        options = {options_decimal[16+3-:4], options_decimal[12+3-:4], options_decimal[8+3-:4], options_decimal[4+3-:4], options_decimal[0+3-:4]};
        goal = 8'h12;
      end
      2'h2: begin
        options_decimal = 20'h4297d;
        options = {options_decimal[16+3-:4], options_decimal[12+3-:4], options_decimal[8+3-:4], options_decimal[4+3-:4], options_decimal[0+3-:4]};
        goal = 4'hd;
      end
      2'h3: begin
        options_decimal = 20'h4567d;
        options = {options_decimal[16+3-:4], options_decimal[12+3-:4], options_decimal[8+3-:4], options_decimal[4+3-:4], options_decimal[0+3-:4]};
        goal = 1'h1;
      end
      3'h4: begin
        options_decimal = 20'h43377;
        options = {options_decimal[16+3-:4], options_decimal[12+3-:4], options_decimal[8+3-:4], options_decimal[4+3-:4], options_decimal[0+3-:4]};
        goal = 4'h8;
      end
      3'h5: begin
        options_decimal = 20'h47538;
        options = {options_decimal[16+3-:4], options_decimal[12+3-:4], options_decimal[8+3-:4], options_decimal[4+3-:4], options_decimal[0+3-:4]};
        goal = 5'h19;
      end
      3'h6: begin
        options_decimal = 20'h13337;
        options = {options_decimal[16+3-:4], options_decimal[12+3-:4], options_decimal[8+3-:4], options_decimal[4+3-:4], options_decimal[0+3-:4]};
        goal = 5'h17;
      end
      3'h7: begin
        options_decimal = 20'h17799;
        options = {options_decimal[16+3-:4], options_decimal[12+3-:4], options_decimal[8+3-:4], options_decimal[4+3-:4], options_decimal[0+3-:4]};
        goal = 5'h1d;
      end
      4'h8: begin
        options_decimal = 20'h46883;
        options = {options_decimal[16+3-:4], options_decimal[12+3-:4], options_decimal[8+3-:4], options_decimal[4+3-:4], options_decimal[0+3-:4]};
        goal = 5'h19;
      end
      4'h9: begin
        options_decimal = 20'h46669;
        options = {options_decimal[16+3-:4], options_decimal[12+3-:4], options_decimal[8+3-:4], options_decimal[4+3-:4], options_decimal[0+3-:4]};
        goal = 5'h1a;
      end
      default: begin
        options_decimal = 20'h12345;
        options = {options_decimal[16+3-:4], options_decimal[12+3-:4], options_decimal[8+3-:4], options_decimal[4+3-:4], options_decimal[0+3-:4]};
        goal = 4'hf;
      end
    endcase
  end
endmodule
